config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resources :coffee

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Shop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Varela+Round'>
    <!-- <link rel="stylesheet" href="jquery/jquery-ui.min.js"> -->

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "posts/header" %>
    <%= render "posts/banner" %>
    <%= yield %>
    <%= render "posts/footer" %>
  </body>
</html>

app/views/posts/_banner.html.erb
<!-- banner  -->
<div class="banner">
  <%= image_tag("coffee.svg", class: "logo", alt: "City") %>
  <h1 class="headline">Coffee Shop</h1>
  <span class="tagline">Lorem ipsum dolor sit amet consectetur adipisicing elit.</span>
</div>

app/views/posts/_footer.html.erb
<!-- footer  -->
<footer class="main-footer">
  <%= link_to "https://www.twitter.com", target: "_blank" do %>
    <%= fa_stacked_icon "twitter", class: "fa-2x", base: "", id: "aqua" %>
  <% end %>
  <%= link_to "https://www.facebook.com", target: "_blank" do %>
    <%= fa_stacked_icon "facebook", class: "fa-2x", base: "", id: "white" %>
  <% end %>
  <%= link_to "https://www.instagram.com", target: "_blank" do %>
    <%= fa_stacked_icon "instagram", class: "fa-2x", base: "", id: "purple" %>
  <% end %>
  <br><br>
  <span>Copyright (c) 2017 Copyright Holder All Rights Reserved.</span>
</footer>

app/views/posts/_header.html.erb
<!-- main header -->
<header class="main-header">
  <div class="container clearfix">
    <!-- <%= link_to "Coffee Shop", "", class: "name" %> -->
    <h1 class="name"><a href="index.html">Coffee Shop</a></h1>
    <ul class="main-nav">
      <li><%= link_to "coffee", coffee_url %></li>
      <li><%= link_to "donuts", "#" %></li>
      <li><%= link_to "cake", "#" %></li>
      <li><%= link_to "tea", "#" %></li>
      <li><%= link_to "about", "#" %></li>
      <!-- <li><a href="donuts.html">donuts</a></li>
      <li><a href="cake.html">cake</a></li>
      <li><a href="tea.html">tea</a></li>
      <li><a href="about.html">about</a></li> -->
      <!-- <li><%= link_to "" do %>
        <%= fa_stacked_icon "user", class: "fa-2x", base: "", id: "lightblue" %>
      <% end %></li> -->
      <li><i class="fa fa-user fa-2x"></i></li>
      <li><i class="fa fa-shopping-cart fa-2x" id="lightblue"></i></li>
    </ul>
  </div>
</header>
<br>

<%= render "posts/header" %>

app/views/posts/about.html.erb
<!-- Our story -->
<div class="container">
  <h1>Our Story</h1>
  <h4>Lorem ipsum 1998 dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br>
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
      eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
  <h4>Lorem ipsum 2000 dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br>
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
      eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
  <h4>Lorem ipsum 2008 dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br>
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
      eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
  <h4>Lorem ipsum 2017 dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br>
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
      eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
</div>

<br>

<!-- Team -->
 <!-- row 1 -->
<div class="container">
<h1>Work Team</h1>
 <div class = "row">
  <div class = "col-sm-6 col-md-3">
    <div class = "thumbnail">
      <img src = "img/team1.jpg" alt = "Generic placeholder thumbnail">
    </div>
      <div class = "caption">
        <h3>Kuno Engelbert</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
        <img src = "img/team2.jpg" alt = "Generic placeholder thumbnail">
      </div>
      <div class = "caption">
         <h3>Greer Berniece</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
        <img src = "img/team3.jpg" alt = "Generic placeholder thumbnail">
      </div>
      <div class = "caption">
         <h3>Larrie Lowell</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
        <img src = "img/team4.jpg" alt = "Generic placeholder thumbnail">
      </div>
      <div class = "caption">
         <h3>Brittney Lana
         </h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
  </div>
</div>

<%= render "posts/about" %>

app/views/posts/cake.html.erb
<!-- cake -->
<!-- row 1 -->
<div class="container">
 <div class = "row">
  <div class = "col-sm-6 col-md-3">
    <div class = "thumbnail">
      <a href="img/cake1.jpg"><img src = "img/cake1.jpg" alt = "Generic placeholder thumbnail"></a>
    </div>
      <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/cake2.jpg"><img src = "img/cake2.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/cake3.jpg"><img src = "img/cake3.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/cake1.jpg"><img src = "img/cake1.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
  </div>
</div>
<!-- row 2-->
<div class="container">
<div class = "row">
 <div class = "col-sm-6 col-md-3">
   <div class = "thumbnail">
     <a href="img/cake1.jpg"><img src = "img/cake1.jpg" alt = "Generic placeholder thumbnail"></a>
   </div>
     <div class = "caption">
       <h3>Thumbnail label</h3>
       <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
          consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/cake2.jpg"><img src = "img/cake2.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/cake3.jpg"><img src = "img/cake3.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/cake1.jpg"><img src = "img/cake1.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
  </div>
</div>

app/views/posts/coffee.html.erb
<!-- Coffees -->
<!-- row 1 -->
<div class="container">
 <div class = "row">
  <div class = "col-sm-6 col-md-3">
    <div class = "thumbnail">
      <%= %>
      <a href="img/coffee1.jpg"><img src = "img/coffee1.jpg" alt = "Generic placeholder thumbnail"></a>
    </div>
      <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/coffee2.jpg"><img src = "img/coffee2.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/coffee3.jpg"><img src = "img/coffee3.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/coffee1.jpg"><img src = "img/coffee1.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
  </div>
</div>
<!-- row 2-->
<div class="container">
<div class = "row">
 <div class = "col-sm-6 col-md-3">
   <div class = "thumbnail">
     <a href="img/coffee1.jpg"><img src = "img/coffee1.jpg" alt = "Generic placeholder thumbnail"></a>
   </div>
     <div class = "caption">
       <h3>Thumbnail label</h3>
       <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
          consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/coffee2.jpg"><img src = "img/coffee2.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/coffee3.jpg"><img src = "img/coffee3.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/coffee1.jpg"><img src = "img/coffee1.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
  </div>
</div>

app/views/posts/donuts.html.erb
<!-- donuts -->
<!-- row 1 -->
<div class="container">
 <div class = "row">
  <div class = "col-sm-6 col-md-3">
    <div class = "thumbnail">
      <!-- <%= image_tag("donuts1.jpg", alt: "Generic placeholder thumbnail" ) %> -->
      <a href="img/donuts1.jpg"><img src = "img/donuts1.jpg" alt = "Generic placeholder thumbnail"></a>
    </div>
      <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/donuts2.jpg"><img src = "img/donuts2.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/donuts3.jpg"><img src = "img/donuts3.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
     <div class = "col-sm-6 col-md-3">
      <div class = "thumbnail">
          <a href="img/donuts1.jpg"><img src = "img/donuts1.jpg" alt = "Generic placeholder thumbnail"></a>
      </div>
      <div class = "caption">
         <h3>Thumbnail label</h3>
         <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
           Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
            consectetur id reprehenderit culpa reprehenderit mollit. </p>
       </div>
     </div>
  </div>
</div>
<!-- row 2-->
<div class="container">
<div class = "row">
 <div class = "col-sm-6 col-md-3">
   <div class = "thumbnail">
     <a href="img/donuts1.jpg"><img src = "img/donuts1.jpg" alt = "Generic placeholder thumbnail"></a>
   </div>
     <div class = "caption">
       <h3>Thumbnail label</h3>
       <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
          consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/donuts2.jpg"><img src = "img/donuts2.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/donuts3.jpg"><img src = "img/donuts3.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
    <div class = "col-sm-6 col-md-3">
     <div class = "thumbnail">
         <a href="img/donuts1.jpg"><img src = "img/donuts1.jpg" alt = "Generic placeholder thumbnail"></a>
     </div>
     <div class = "caption">
        <h3>Thumbnail label</h3>
        <p>Magna id veniam labore ut ad cillum minim ea irure enim. Nulla adipisicing aute nostrud Lorem velit.
          Exercitation mollit reprehenderit enim incididunt laborum nostrud nisi duis excepteur. Ex quis minim
           consectetur id reprehenderit culpa reprehenderit mollit. </p>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<!-- Main page content -->
<!-- container  -->
<div class="container clearfix">
  <!-- secundary column -->
  <div class="secondary col">
    <h2>Lorem Ipsum</h2>
    <p>Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <!-- primary column -->
  <div class="primary col">
    <h2>Lorem Ipsum</h2>

  <!-- featured image -->
  <figure>
    <%= image_tag("location.svg", class: "icon-location", alt: "Location") %>
    <%= image_tag("treats.png", class: "feat-img", alt: "Coffee and eats") %>
    <figcaption>
      <h4>Featured Coffees &amp; Eats!</h4>
      Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </figcaption>
  </figure>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div> <!--primary column -->

<!-- tertiary column -->
<div class="tertiary col">
  <h2>How to get here</h2>
  <p><strong>Plane: </strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
  <p><strong>Train: </strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
  <p><strong>Car: </strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
</div>

</div> <!-- container  -->